#!/usr/bin/env python3
import os
import re

def compile_deck():
    slides_dir = "slides"
    output_file = "index_offline.html"

    # Define standard Reveal.js template
    html_template = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Google Cloud Executive Presentation (Editable Deck)</title>

    <!-- Google Fonts for premium design aesthetics -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;700&family=Outfit:wght@400;600;800&display=swap" rel="stylesheet">

    <!-- Reveal.js stylesheet links (CDN) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reset.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.css">
    
    <!-- Premium Google Brand Colors & Variable CSS -->
    <style>
      :root {
        --google-blue: #1a73e8;
        --google-red: #ea4335;
        --google-yellow: #fbbc05;
        --google-green: #34a853;
        --text-color: #1f1f1f;
        --bg-color: #ffffff;
      }
      body {
        font-family: 'Inter', sans-serif;
        color: var(--text-color);
        background: var(--bg-color);
      }
      h1, h2, h3, h4, h5, h6 {
        font-family: 'Outfit', sans-serif;
        font-weight: 600;
        color: var(--google-blue);
      }
      
      /* Visual state indicator styling */
      #save-status-indicator {
        position: fixed;
        top: 20px;
        right: 20px;
        z-index: 9999;
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 8px 12px;
        border-radius: 20px;
        background: rgba(255, 255, 255, 0.9);
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
        border: 1px solid rgba(0, 0, 0, 0.05);
        font-family: 'Inter', sans-serif;
        font-size: 13px;
        font-weight: 500;
        transition: all 0.3s ease;
      }
      #save-status-indicator .dot {
        width: 8px;
        height: 8px;
        border-radius: 50%;
        display: inline-block;
      }
      #save-status-indicator.saved .dot {
        background-color: var(--google-green);
        box-shadow: 0 0 8px var(--google-green);
      }
      #save-status-indicator.saving .dot {
        background-color: var(--google-yellow);
        box-shadow: 0 0 8px var(--google-yellow);
        animation: pulse 1.2s infinite ease-in-out;
      }
      #save-status-indicator.error .dot {
        background-color: var(--google-red);
        box-shadow: 0 0 8px var(--google-red);
      }
      
      @keyframes pulse {
        0%, 100% { opacity: 0.4; transform: scale(0.9); }
        50% { opacity: 1; transform: scale(1.1); }
      }
    </style>
  </head>
  <body>
    <div id="save-status-indicator" class="saved">
      <span class="dot"></span>
      <span class="text">Saved to Disk</span>
    </div>

    <div class="reveal">
      <div class="slides">
        <!-- ALL SLIDES AUTOGENERATED FROM slides/ DIRECTORY -->
        {slides_content}
      </div>
    </div>

    <!-- Reveal.js engine (CDN) -->
    <script src="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.js"></script>
    <script>
      // Initialize Reveal.js
      Reveal.initialize({
        hash: true,
        history: true,
        transition: 'slide', // none/fade/slide/convex/concave/zoom
        backgroundTransition: 'fade'
      });
    </script>
    
    <!-- Auto-Persistence Front-end Client Script -->
    <script src="js/editable-client.js"></script>
  </body>
</html>"""

    # Ensure slides directory exists
    if not os.path.exists(slides_dir):
        os.makedirs(slides_dir)
        # Create a default slide fragment if empty
        with open(os.path.join(slides_dir, "slide-1.html"), "w") as f:
            f.write('<section>\n  <h1 contenteditable="true">Welcome to your Slide Deck</h1>\n  <p contenteditable="true">This text is directly editable on the screen. Double-click and type!</p>\n</section>\n')

    # Read and sort slide files numerically
    slide_files = []
    for filename in os.listdir(slides_dir):
        if filename.startswith("slide-") and filename.endswith(".html"):
            # Extract slide number
            match = re.search(r'slide-(\d+)\.html', filename)
            if match:
                slide_files.append((int(match.group(1)), filename))

    # Sort slide files by number
    slide_files.sort(key=lambda x: x[0])

    # Aggregate slide contents
    slides_html = []
    for num, filename in slide_files:
        filepath = os.path.join(slides_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()
            # Wrap content with standard slide attribute identifiers if missing
            if not content.startswith("<section"):
                content = f'<section data-slide-index="{num}">\n{content}\n</section>'
            else:
                # Inject data-slide-index for programmatic frontend mapping
                if "data-slide-index" not in content:
                    content = content.replace("<section", f'<section data-slide-index="{num}"', 1)
            slides_html.append(content)

    all_slides_content = "\n\n        ".join(slides_html)

    # Format template
    compiled_html = html_template.format(slides_content=all_slides_content)

    # Write output compiled deck
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(compiled_html)
    
    print(f"🎉 Successfully aggregated {len(slide_files)} slide fragments into '{output_file}'!")

if __name__ == "__main__":
    compile_deck()
